server.port=60123
spring.application.name=customized
# 中信
#spring.datasource.url=jdbc:postgresql://172.17.121.1:7092/csc_hik_proxy
# 泰康
spring.datasource.url=jdbc:postgresql://172.17.121.2:7092/csc_hik_proxy
spring.datasource.username=csc_admin
spring.datasource.password=Acsys_00
spring.datasource.driver-class-name=org.postgresql.Driver
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus.configuration.map-underscore-to-camel-case=true
# 中信配置
artemis.config={"host":"172.17.121.1:443","appKey":"27084252","appSecret":"TwWHFXio2Rgm11M2u3N9"}
artemis.protocol=https
download.host=http://172.17.121.1:8950
req.check=true